export const DESIGN_TOKENS = Object.freeze({
  surface0: "#181818",
  surface1: "#1f1f1f",
  surface2: "#242424",
  surface3: "#2a2a2a",
  line: "rgba(255, 255, 255, 0.08)",
  lineStrong: "rgba(255, 255, 255, 0.12)",
  textPrimary: "#ffffff",
  textSecondary: "rgba(255, 255, 255, 0.68)",
  textMeta: "rgba(255, 255, 255, 0.45)",
  dangerText: "#ffc9c9",
  dangerBorder: "rgba(255, 107, 107, 0.38)",
  dangerSoft: "rgba(255, 107, 107, 0.12)",
  shadowPanel: "0 14px 36px rgba(0, 0, 0, 0.22)",
  assemblyStep0Text: "#aeb4be",
  assemblyStep1: "#5ea7ff",
  assemblyStep1Soft: "rgba(94, 167, 255, 0.14)",
  assemblyStep1Border: "rgba(94, 167, 255, 0.28)",
  assemblyStep1Text: "#7eb8ff",
  assemblyStep2Text: "#5fd1ff",
  assemblyStep3Text: "#58dcc9",
  assemblyStep3Border: "rgba(47, 209, 187, 0.3)",
  assemblyStep3Soft: "rgba(47, 209, 187, 0.15)",
  assemblyStep4Text: "#7ad881",
  assemblyStep4Border: "rgba(97, 201, 106, 0.3)",
  assemblyStep4Soft: "rgba(97, 201, 106, 0.15)",
  assemblyStep6Text: "#ebad5a",
  assemblyStep7Text: "#ffab73",
});

export const WORKSPACE_LOG_ACTION_COLORS = Object.freeze({
  UPLOADED: DESIGN_TOKENS.assemblyStep0Text,
  UPLOADED_IMAGE: DESIGN_TOKENS.assemblyStep6Text,
  LINK_ADDED: DESIGN_TOKENS.assemblyStep2Text,
  UPLOADED_AUDIO: DESIGN_TOKENS.assemblyStep7Text,
  PASTED: DESIGN_TOKENS.assemblyStep3Text,
  PASTED_IMAGE: DESIGN_TOKENS.assemblyStep3Text,
  LISTENED: DESIGN_TOKENS.assemblyStep1Text,
  AI_QUERY: DESIGN_TOKENS.assemblyStep1Text,
  AI_RESULT: DESIGN_TOKENS.assemblyStep4Text,
  DERIVED_IMAGE_SOURCE: DESIGN_TOKENS.assemblyStep6Text,
  DERIVED_LINK_SOURCE: DESIGN_TOKENS.assemblyStep2Text,
  DERIVED_AUDIO_SOURCE: DESIGN_TOKENS.assemblyStep7Text,
  SELECTED: DESIGN_TOKENS.assemblyStep3Text,
  EDITED: DESIGN_TOKENS.assemblyStep7Text,
  CLEANED: DESIGN_TOKENS.assemblyStep6Text,
  REPLACED: DESIGN_TOKENS.assemblyStep1Text,
  DELETED: DESIGN_TOKENS.dangerText,
  POLISHED: DESIGN_TOKENS.assemblyStep6Text,
  ASSEMBLED: DESIGN_TOKENS.assemblyStep6Text,
  OPERATED: DESIGN_TOKENS.assemblyStep1Text,
  RECEIPT: DESIGN_TOKENS.assemblyStep4Text,
  CONFIRMED: DESIGN_TOKENS.assemblyStep4Text,
  DISCARDED: DESIGN_TOKENS.dangerText,
  ROOT_DECLARED: DESIGN_TOKENS.assemblyStep1Text,
  RECEIPT_SEALED: DESIGN_TOKENS.assemblyStep4Text,
});
