import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

async function read(path) {
  return readFile(new URL(`../${path}`, import.meta.url), "utf8");
}

test("section dream is a signed-in utility route wired into signed-in navigation only", async () => {
  const dreamPage = await read("src/app/dream/page.jsx");
  const dreamScreen = await read("src/components/dream/SectionDreamScreen.jsx");
  const compilerPanel = await read("src/components/dream/CompilerReadPanel.jsx");
  const compilerSelfCheck = await read("src/lib/compiler-read-self-check.js");
  const compilerDiagnostics = await read("src/lib/compiler-read-diagnostics.js");
  const shell = await read("src/components/shell/LoegosShell.jsx");
  const roomWorkspace = await read("src/components/room/RoomWorkspace.jsx");
  const runtimeResume = await read("src/lib/runtime-surface-resume.js");
  const publicSite = await read("src/lib/public-site.js");
  const roomServer = await read("src/lib/room-server.js");

  assert.match(dreamPage, /SectionDreamScreen/);
  assert.match(dreamPage, /title: "Library"/);
  assert.match(dreamPage, /getRequiredSession/);
  assert.match(dreamPage, /redirect\("\/"\)/);
  assert.match(dreamPage, /includeDevice:\s*false/);

  assert.match(dreamScreen, /LoegosShell/);
  assert.match(dreamScreen, /<Kicker tone="brand">Library<\/Kicker>/);
  assert.match(dreamScreen, /dream-library-toggle/);
  assert.match(dreamScreen, /dream-open-library-manager/);
  assert.match(dreamScreen, /dream-compiler-read/);
  assert.match(dreamScreen, /CompilerReadPanel/);
  assert.match(dreamScreen, /dream-compiler-read-repair-row/);
  assert.match(dreamScreen, /dream-compiler-read-update-rerun/);
  assert.match(dreamScreen, /dream-compiler-read-discard-edits/);
  assert.match(dreamScreen, /dream-fresh-import-actions/);
  assert.match(dreamScreen, /dream-copy-read/);
  assert.match(dreamScreen, /dream-restore-previous-version/);
  assert.match(dreamScreen, /dream-discuss-read/);
  assert.match(dreamScreen, /dream-choose-document/);
  assert.match(dreamScreen, /dream-replace-document/);
  assert.match(dreamScreen, /window\.matchMedia\("\(min-width: 960px\)"\)\.matches/);
  assert.match(dreamScreen, /createNextDreamDocumentVersion/);
  assert.match(dreamScreen, /attachCompilerReadToDreamDocument/);
  assert.match(dreamScreen, /restorePreviousDreamDocumentVersion/);
  assert.match(dreamScreen, /clearCompilerReadSelfCheck\(\s*dreamDocument\.id,/);
  assert.match(dreamScreen, /clearRuntimeSurfaceResumeLibrary\(\)/);
  assert.match(dreamScreen, /All Library documents/);
  assert.match(dreamScreen, /Delete from Library/);
  assert.match(dreamScreen, /Library only/);
  assert.doesNotMatch(dreamScreen, /ReplayReviewPanel/);
  assert.match(compilerPanel, /useSyncExternalStore/);
  assert.match(compilerPanel, /loadCompilerReadSelfCheck/);
  assert.match(compilerPanel, /saveCompilerReadSelfCheck/);
  assert.match(compilerPanel, /buildCompilerReadDiagnosticsView/);
  assert.match(compilerPanel, /Show all parser events/);
  assert.match(compilerPanel, /dream-compiler-read-diagnostics-\$\{bucket\.id\}/);
  assert.match(compilerPanel, /dream-compiler-read-diagnostics-all/);
  assert.match(compilerPanel, /showSelfCheck/);
  assert.match(compilerPanel, /summaryRef/);
  assert.match(compilerPanel, /compilerReadKey/);
  assert.match(compilerPanel, /dream-compiler-read-stale/);
  assert.match(compilerPanel, /dream-compiler-read-delta/);
  assert.match(compilerPanel, /dream-compiler-read-actions/);
  assert.match(compilerSelfCheck, /clearCompilerReadSelfCheck/);
  assert.match(compilerDiagnostics, /Raw prose \/ formatting noise/);
  assert.match(compilerDiagnostics, /Structural blockers/);
  assert.match(compilerDiagnostics, /Translated subset diagnostics/);
  assert.match(compilerPanel, /claim\.text \|\| "Untitled claim"/);
  assert.match(compilerPanel, /claim\.reason \|\| "This claim could not travel cleanly in the current subset\."/);
  assert.doesNotMatch(compilerPanel, /claim\.claimText/);
  assert.doesNotMatch(compilerPanel, /claim\.omissionReason/);
  assert.match(shell, /shell-mode-room/);
  assert.match(shell, /shell-mode-dream/);
  assert.doesNotMatch(shell, /shell-mobile-account/);
  assert.match(shell, /Account/);
  assert.match(shell, /signOut\(\{ callbackUrl: "\/" \}\)/);
  assert.match(shell, /event\.key !== "Tab"/);
  assert.match(roomWorkspace, /room-open-context/);
  assert.match(roomWorkspace, /room-new-conversation/);
  assert.match(roomWorkspace, /room-post-add-card/);
  assert.match(roomWorkspace, /room-resume-banner/);
  assert.match(roomWorkspace, /room-starter-fork/);
  assert.match(roomWorkspace, /room-starter-live-issue/);
  assert.match(roomWorkspace, /room-starter-source-document/);
  assert.match(roomWorkspace, /function WorkingEchoStrip/);
  assert.match(roomWorkspace, /buildWorkingEchoStripStateFromRoomView/);
  assert.match(roomWorkspace, /dream-bridge-return/);
  assert.match(roomWorkspace, /dream-bridge-use/);
  assert.match(roomWorkspace, /dream-bridge-dismiss/);
  assert.match(roomWorkspace, /dream-bridge-restore/);
  assert.match(roomWorkspace, /Bridge dismissed/);
  assert.match(roomWorkspace, /Pending: available but not active\./);
  assert.match(roomWorkspace, /Armed: travels with your next turn\./);
  assert.match(roomWorkspace, /pendingDreamBridgePayload\?\.state === "armed"/);
  assert.match(roomWorkspace, /previous\?\.lastSurface === "dream"/);
  assert.match(roomWorkspace, /clearRuntimeSurfaceResumeLibrary\(\)/);
  assert.match(roomWorkspace, /buildDreamDocumentRecord/);
  assert.match(roomWorkspace, /saveDreamDocument/);
  assert.match(roomWorkspace, /Tell Seven what is live right now/);
  assert.match(roomWorkspace, /Ask Seven about this source or name the issue/);
  assert.match(roomWorkspace, /Continue the live issue or add new source/);
  assert.doesNotMatch(roomWorkspace, /setComposerText\(\(current\) => current \|\| excerpt/);
  assert.doesNotMatch(roomWorkspace, /const bridgePayload = pendingDreamBridgePayload;/);
  assert.match(dreamScreen, /const visibleCompilerRead = dreamDocument\?\.compilerRead \|\| null/);
  assert.match(dreamScreen, /const isCompilerReadStale = Boolean\(hasUnsavedPasteChanges && visibleCompilerRead\)/);
  assert.match(runtimeResume, /clearRuntimeSurfaceResumeLibrary/);

  assert.doesNotMatch(publicSite, /\/dream/);
  assert.doesNotMatch(roomServer, /\/dream/);
});
