import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

async function read(path) {
  return readFile(new URL(`../${path}`, import.meta.url), "utf8");
}

test("section dream is a signed-in utility route wired into signed-in navigation only", async () => {
  const dreamPage = await read("src/app/dream/page.jsx");
  const libraryPage = await read("src/app/library/page.jsx");
  const dreamScreen = await read("src/components/dream/SectionDreamScreen.jsx");
  const compilerPanel = await read("src/components/dream/CompilerReadPanel.jsx");
  const compilerSelfCheck = await read("src/lib/compiler-read-self-check.js");
  const compilerDiagnostics = await read("src/lib/compiler-read-diagnostics.js");
  const shell = await read("src/components/shell/LoegosShell.jsx");
  const roomWorkspace = await read("src/components/room/RoomWorkspace.jsx");
  const runtimeResume = await read("src/lib/runtime-surface-resume.js");
  const publicSite = await read("src/lib/public-site.js");
  const roomServer = await read("src/lib/room-server.js");
  const libraryArtifactPane = await read("src/components/workspace/LibraryArtifactPane.jsx");

  assert.match(dreamPage, /redirect\(`\/library/);
  assert.match(dreamPage, /title: "Library"/);
  assert.match(dreamPage, /resolvedSearchParams\?\.project/);
  assert.match(dreamPage, /params\.set\("sessionId", sessionId\)/);
  assert.match(libraryPage, /artifactType/);
  assert.match(libraryPage, /redirect\(`\/workspace/);
  assert.match(libraryPage, /resolvedSearchParams\?\.project/);
  assert.match(libraryPage, /params\.set\("sessionId", sessionId\)/);

  assert.match(dreamScreen, /LoegosShell/);
  assert.match(dreamScreen, /<strong>Documents<\/strong>/);
  assert.match(dreamScreen, /dream-open-library-manager/);
  assert.match(dreamScreen, /dream-compiler-read/);
  assert.match(dreamScreen, /dream-bottom-plus/);
  assert.match(dreamScreen, /dream-bottom-menu-upload/);
  assert.match(dreamScreen, /dream-bottom-menu-paste/);
  assert.match(dreamScreen, /CompilerReadPanel/);
  assert.match(dreamScreen, /dream-bottom-save-version/);
  assert.match(dreamScreen, /dream-bottom-save-run-read/);
  assert.match(dreamScreen, /dream-bottom-save-document/);
  assert.match(dreamScreen, /dream-compiler-read-update-rerun/);
  assert.match(dreamScreen, /dream-bottom-discard-edits/);
  assert.match(dreamScreen, /dream-bottom-edge/);
  assert.match(dreamScreen, /dream-open-current-read/);
  assert.match(dreamScreen, /dream-bottom-menu-open-document/);
  assert.doesNotMatch(dreamScreen, /scopeControl=\{scopeControl\}/);
  assert.match(dreamScreen, /dream-copy-read/);
  assert.match(dreamScreen, /dream-restore-previous-version/);
  assert.match(dreamScreen, /dream-discuss-read/);
  assert.match(dreamScreen, /dream-choose-document/);
  assert.match(dreamScreen, /dream-replace-document/);
  assert.match(dreamScreen, /dreamDocument\?\.currentVersionLabel/);
  assert.match(dreamScreen, /window\.matchMedia\("\(min-width: 960px\)"\)\.matches/);
  assert.match(dreamScreen, /createNextDreamDocumentVersion/);
  assert.match(dreamScreen, /attachCompilerReadToDreamDocument/);
  assert.match(dreamScreen, /restorePreviousDreamDocumentVersion/);
  assert.match(dreamScreen, /clearCompilerReadSelfCheck\(\s*dreamDocument\.id,/);
  assert.match(dreamScreen, /clearRuntimeSurfaceResumeLibrary\(\)/);
  assert.match(dreamScreen, /No saved documents yet/);
  assert.match(dreamScreen, /Delete from Library/);
  assert.match(dreamScreen, /Library only/);
  assert.doesNotMatch(dreamScreen, /ReplayReviewPanel/);
  assert.match(compilerPanel, /useSyncExternalStore/);
  assert.match(compilerPanel, /loadCompilerReadSelfCheck/);
  assert.match(compilerPanel, /saveCompilerReadSelfCheck/);
  assert.match(compilerPanel, /buildCompilerReadDiagnosticsView/);
  assert.match(compilerPanel, /Show all parser events/);
  assert.match(compilerPanel, /dream-compiler-read-diagnostics-\$\{bucket\.id\}/);
  assert.match(compilerPanel, /dream-compiler-read-diagnostics-all/);
  assert.match(compilerPanel, /showSelfCheck/);
  assert.match(compilerPanel, /summaryRef/);
  assert.match(compilerPanel, /compilerReadKey/);
  assert.match(compilerPanel, /dream-compiler-read-stale/);
  assert.match(compilerPanel, /dream-compiler-read-delta/);
  assert.match(compilerPanel, /dream-compiler-read-actions/);
  assert.match(compilerPanel, /dream-compiler-read-supported-terms/);
  assert.match(compilerPanel, /dream-compiler-read-unsupported-efficacy/);
  assert.match(compilerPanel, /dream-compiler-read-missing-witness/);
  assert.match(compilerSelfCheck, /clearCompilerReadSelfCheck/);
  assert.match(compilerDiagnostics, /Raw prose \/ formatting noise/);
  assert.match(compilerDiagnostics, /Structural blockers/);
  assert.match(compilerDiagnostics, /Translated subset diagnostics/);
  assert.match(compilerPanel, /claim\.text \|\| "Untitled claim"/);
  assert.match(compilerPanel, /What the source states explicitly/);
  assert.match(compilerPanel, /What still needs evidence before deciding/);
  assert.match(compilerPanel, /Show extracted claims under review/);
  assert.doesNotMatch(compilerPanel, /claim\.claimText/);
  assert.doesNotMatch(compilerPanel, /claim\.omissionReason/);
  assert.match(shell, /shell-mode-room/);
  assert.match(shell, /shell-mode-dream/);
  assert.match(shell, /shell-rail-toggle/);
  assert.match(shell, /shell-mobile-drawer-trigger/);
  assert.doesNotMatch(shell, /shell-mobile-room/);
  assert.doesNotMatch(shell, /shell-mobile-dream/);
  assert.doesNotMatch(shell, /shell-mobile-account/);
  assert.match(shell, /Account/);
  assert.match(shell, /signOut\(\{ callbackUrl: "\/" \}\)/);
  assert.match(shell, /event\.key !== "Tab"/);
  assert.match(roomWorkspace, /WorkspaceTriangleShell/);
  assert.match(roomWorkspace, /workspace-utility-settings/);
  assert.match(roomWorkspace, /workspace-knowledge-rail/);
  assert.match(roomWorkspace, /workspace-continuity-rail/);
  assert.match(roomWorkspace, /room-post-add-card/);
  assert.match(roomWorkspace, /room-resume-banner/);
  assert.match(roomWorkspace, /room-starter-fork/);
  assert.match(roomWorkspace, /room-starter-live-issue/);
  assert.match(roomWorkspace, /room-starter-paste/);
  assert.match(roomWorkspace, /room-starter-upload/);
  assert.match(roomWorkspace, /function WorkingEchoStrip/);
  assert.match(roomWorkspace, /buildWorkingEchoStripStateFromRoomView/);
  assert.match(roomWorkspace, /dream-bridge-return/);
  assert.match(roomWorkspace, /dream-bridge-use/);
  assert.match(roomWorkspace, /dream-bridge-dismiss/);
  assert.match(roomWorkspace, /dream-bridge-restore/);
  assert.match(roomWorkspace, /dream-bridge-clear-dismissed/);
  assert.match(roomWorkspace, /room-dream-bridge/);
  assert.match(roomWorkspace, /room-dream-bridge-recovery/);
  assert.match(roomWorkspace, /composerPrelude/);
  assert.match(roomWorkspace, /pendingDreamBridgePayload\?\.state === "armed"/);
  assert.match(roomWorkspace, /incomingPayload.state === "dismissed"/);
  assert.match(roomWorkspace, /previous\?\.lastSurface === "dream"/);
  assert.match(roomWorkspace, /clearRuntimeSurfaceResumeLibrary\(\)/);
  assert.match(roomWorkspace, /buildDreamDocumentRecord/);
  assert.match(roomWorkspace, /saveDreamDocument/);
  assert.match(roomWorkspace, /const currentLibraryHref = buildLibraryHref/);
  assert.match(roomWorkspace, /requestedArtifactId=\{focusedArtifact\?\.id \|\| routeArtifactId\}/);
  assert.match(libraryArtifactPane, /Requested Library artifact not found\./);
  assert.match(libraryArtifactPane, /The requested Library artifact is no longer available\./);
  assert.match(roomWorkspace, /scopeLabel=\{shell\?\.composerScope\?\.label \|\| assemblyTitle\}/);
  assert.match(roomWorkspace, /scopeDetail=\{shell\?\.composerScope\?\.detail \|\| scopeSummary\}/);
  assert.match(roomWorkspace, /LibraryArtifactPane/);
  assert.match(roomWorkspace, /room-artifact-/);
  assert.match(roomWorkspace, /Tell Seven what is live right now/);
  assert.match(roomWorkspace, /Bring one live thing into focus\./);
  assert.doesNotMatch(roomWorkspace, /BRIDGE_DISMISS_RECOVERY_MS/);
  assert.doesNotMatch(roomWorkspace, /setComposerText\(\(current\) => current \|\| excerpt/);
  assert.doesNotMatch(roomWorkspace, /const bridgePayload = pendingDreamBridgePayload;/);
  assert.match(dreamScreen, /const visibleCompilerRead = dreamDocument\?\.compilerRead \|\| null/);
  assert.match(dreamScreen, /const isCompilerReadStale = Boolean\(hasUnsavedPasteChanges && visibleCompilerRead\)/);
  assert.match(runtimeResume, /clearRuntimeSurfaceResumeLibrary/);

  assert.doesNotMatch(publicSite, /\/dream/);
  assert.doesNotMatch(roomServer, /\/dream/);
});
